### ISSUE TITLE
LightBDD 3.0 epic

### ISSUE THREAD

**Issue by Suremaker** [LightBDD/LightBDD#152]
#### Description
As LightBDD 2.x has been developed over a while a set of obsolete methods has been introduced together with the over-complicated abstractions that were required to implement a new functionality while being backward compatible with previous versions.

This ticket is an epic collecting all the problems to be addressed with v 3.0: 
- [x] Remove obsoleted code,
- [x] Unify scenario/step methods and namespaces
  - [x] Unify namespaces,
  - [x] Make all scenarios fluent by default, allowing to mix and match,
  - [x] Remove  `RunScenarioActionsAsync()` methods
  - [x] Review Runner methods (sync/async) and simplify in-code docs
- [x] Simplify scenario/step execution stack trace
  - [x] inline framework specific decorators,
  - [ ] ~~change decorators to pass next one via ctor~~,
  - [x] revisit internal call stacks
- [x] Simplify framework-core abstractions
  - [x] Remove `Enrich()` methods,
  - [x] Rework, simplify and unify internals of the scenario / step methods,
  - [x] Remove optional enabling of commenting feature and other basic features,
  - [x] Rework how LightBDDConfiguration is being passed to framework and implementations,
- [x] Update templates,
- [x] Update examples,
- [x] Review DebuggerStepThrough and debugging experience

### Unify scenario/step methods and namespaces

* Unify `Basic/Extended/Contextual/Fluent` namespaces with `LightBDD.Framework.Scenarios`,
* Make all scenarios fluent by default, allowing to mix and match:
  * remove `NewScenario()`
  * allow `Runner.WithSteps().RunScenarioAsync()`
  * allow `Runner.WithContext<T>().WithSetup(x=>x...).WithTearDown(x=>x...).WithSteps(/*basic*/).WithSteps(/*extended*/).RunScenarioAsync()`
* Allow simple scenario execution `Runner.RunScenarioAsync(/*steps*/)`
* Remove `RunScenarioActionsAsync()` methods 
* Consider removing `Runner.RunScenario()` (sync) version

### Simplify scenario/step execution stack trace
Rework internals to ensure that call stack to the step is relatively flat:
* inline framework specific decorators,
* change decorators to pass next one via ctor,
* revisit internal call stacks.

### Simplify framework-core abstractions

* Remove `Enrich()` methods,
* Rework, simplify and unify internals of the scenario / step methods,
* Remove optional enabling of commenting feature and other basic features,
* Rework how LightBDDConfiguration is being passed to framework and implementations,
* ... and anything else that can be simplified here

**Comment by dday4thedeceiver** [comment]
Runner.WithSteps() sounds like it'll let you inline the steps?

I'm just getting started with LightBDD and that's one of my only objections so far. I'm moving all my unit tests to a BDD structure with either class per story or class per scenario, and going from classic xUnit to Light BDD adds additional verbosity when a step isn't shared (which is most of the time) and could be inlined.

BDDfy does this but they got it backwards - the first parameter is the function and the second parameter is the step title, which reduces readability big time.

SubSpec defines G/W/T (or C/D/A in their parlance) extension methods for strings.

**Comment by Suremaker** [comment]
Hello @dday4thedeceiver, 

The point about `WithSteps()` method is basically to make the existing [fluent syntax](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#fluent-scenarios) a bit easier to use, which is however not about inlining the steps.

The LightBDD is designed around methods representing scenarios or steps where method name represent the scenario / step name and the method parameters are captured as the scenario / step parameters (more is described on [wiki](https://github.com/LightBDD/LightBDD/wiki/Tests-Structure-and-Conventions)). The problem with inlined steps is that they do not have name then to represent them nicely in the reports...

By default, LightBDD does not support string names for the steps nor inlined steps as using strings makes code less readable and more difficult to refactor/rename and work with, while using inline steps will make scenarios themselves verbose. 

Having said that, I see your point about keeping the scenario method self-contained and it is a valid point. I will take a look at the https://github.com/LightBDD/LightBDD/issues/155 to make it working with local functions. I will also come back to you in the evening with some answers how to do the inline steps with text names in case you really want to structure your code this way.
